defaults: &default_settings
  adapter: postgresql
  host: db
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: utf8
  pool: 25
  timeout: 5000
  min_messages: WARNING

development:
  <<: *default_settings
  database: demo_docker_development

staging:
  <<: *default_settings
  database: demo_docker_staging

production:
  <<: *default_settings
  database: demo_docker_production

test:
  <<: *default_settings
  database: demo_docker_test
